#mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.200:3306/websocket_item?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: localhost
      port: 6379
      database: 3
  servlet:
    multipart:
      enabled: true #开启多文件上传
      max-file-size: 10MB #限制单个文件上传大小为10MB
      max-request-size: 100MB #限制一次多文件上传总数据大小为100MB

# 分页类默认配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# SQL日志打印
logging:
  level:
    com.example.websocketitem: debug
server:
  port: 8089
    # 配置 Https 证书
#  ssl:
#    key-store: classpath:client.p12
#    key-store-password: 123123
#    #    key-store-type: JKS
#    key-alias: client


